In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, mean_absolute_percentage_error

In [ ]:
train_data = pd.read_csv("/content/train_data.csv")
test_data_1 = pd.read_csv("/content/test_data.csv")
train_data.head()

id   airline   flight source_city departure_time stops arrival_time  \
0   1   Vistara   UK-810   Bangalore  Early_Morning   one        Night   
1   2  SpiceJet  SG-5094   Hyderabad        Evening  zero        Night   
2   3   Vistara   UK-846   Bangalore        Morning   one      Evening   
3   4   Vistara   UK-706     Kolkata        Morning   one      Evening   
4   5    Indigo  6E-5394     Chennai  Early_Morning  zero      Morning   

  destination_city     class  duration  days_left  price  
0           Mumbai   Economy     14.25         21   7212  
1          Kolkata   Economy      1.75          7   5292  
2            Delhi  Business      9.58          5  60553  
3        Hyderabad   Economy      6.75         28   5760  
4           Mumbai   Economy      2.00          4  10712

In [ ]:
test_data = test_data_1.copy()

In [ ]:
test_data.head()

id    airline  flight source_city departure_time stops   arrival_time  \
0   1  Air_India  AI-765     Kolkata        Evening   one          Night   
1   2    Vistara  UK-747       Delhi  Early_Morning   one          Night   
2   3  Air_India  AI-570      Mumbai  Early_Morning  zero  Early_Morning   
3   4    AirAsia  I5-974   Hyderabad          Night   one     Late_Night   
4   5  Air_India  AI-770     Kolkata          Night   one      Afternoon   

  destination_city     class  duration  days_left  
0            Delhi  Business     28.25          2  
1           Mumbai  Business     13.83         34  
2          Chennai  Business      2.00         30  
3            Delhi   Economy      5.17         26  
4           Mumbai   Economy     16.33         35

In [ ]:
print(train_data.shape)
print(test_data.shape)

(20000, 12)
(5000, 11)


In [ ]:
train_data.info()
train_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                20000 non-null  int64  
 1   airline           20000 non-null  object 
 2   flight            20000 non-null  object 
 3   source_city       20000 non-null  object 
 4   departure_time    20000 non-null  object 
 5   stops             20000 non-null  object 
 6   arrival_time      20000 non-null  object 
 7   destination_city  20000 non-null  object 
 8   class             20000 non-null  object 
 9   duration          20000 non-null  float64
 10  days_left         20000 non-null  int64  
 11  price             20000 non-null  int64  
dtypes: float64(1), int64(3), object(8)
memory usage: 1.8+ MB


id      duration     days_left          price
count  20000.000000  20000.000000  20000.000000   20000.000000
mean   10000.500000     12.177627     25.924150   20960.281700
std     5773.647028      7.157944     13.624874   22775.459535
min        1.000000      0.830000      1.000000    1105.000000
25%     5000.750000      6.830000     14.000000    4783.000000
50%    10000.500000     11.250000     26.000000    7425.000000
75%    15000.250000     16.080000     38.000000   42521.000000
max    20000.000000     38.580000     49.000000  114523.000000

In [ ]:
print(train_data.isna().sum())
print('---')
print(test_data.isna().sum())

id                  0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64
---
id                  0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
dtype: int64


In [ ]:
train_data.corr()['price'].abs()

<ipython-input-24-5b3a72ba37bc>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  train_data.corr()['price'].abs()


id           0.002443
duration     0.213158
days_left    0.102545
price        1.000000
Name: price, dtype: float64

In [ ]:
# print(len(train_data['airline'].unique()))
# print(len(train_data['flight'].unique()))
# print(len(train_data['source_city'].unique()))
# print(len(train_data['departure_time'].unique()))
# print(len(train_data['stops'].unique()))
# print(len(train_data['arrival_time'].unique()))
# print(len(train_data['destination_city'].unique()))
# print(len(train_data['class'].unique()))

for column in train_data.columns:
  print(len(train_data[column].unique()))

6
1310
6
6
3
6
6
2
404
49
4420


In [ ]:
train_data.drop(['id'],axis=1, inplace=True)
test_data.drop(['id'],axis=1, inplace=True)

In [ ]:
train_data.head()

airline   flight source_city departure_time stops arrival_time  \
0   Vistara   UK-810   Bangalore  Early_Morning   one        Night   
1  SpiceJet  SG-5094   Hyderabad        Evening  zero        Night   
2   Vistara   UK-846   Bangalore        Morning   one      Evening   
3   Vistara   UK-706     Kolkata        Morning   one      Evening   
4    Indigo  6E-5394     Chennai  Early_Morning  zero      Morning   

  destination_city     class  duration  days_left  price  
0           Mumbai   Economy     14.25         21   7212  
1          Kolkata   Economy      1.75          7   5292  
2            Delhi  Business      9.58          5  60553  
3        Hyderabad   Economy      6.75         28   5760  
4           Mumbai   Economy      2.00          4  10712

In [ ]:
encoder = OrdinalEncoder()
train_data[["airline",	"flight",	"source_city",	"departure_time",	"stops",	"arrival_time",	"destination_city",	"class"]]=encoder.fit_transform(train_data[["airline",	"flight",	"source_city",	"departure_time",	"stops",	"arrival_time",	"destination_city",	"class"]])

In [ ]:
train_data.head()

airline  flight  source_city  departure_time  stops  arrival_time  \
0      5.0  1214.0          0.0             1.0    0.0           5.0   
1      4.0  1126.0          3.0             2.0    2.0           5.0   
2      5.0  1245.0          0.0             4.0    0.0           2.0   
3      5.0  1191.0          4.0             4.0    0.0           2.0   
4      3.0   275.0          1.0             1.0    2.0           4.0   

   destination_city  class  duration  days_left  price  
0               5.0    1.0     14.25         21   7212  
1               4.0    1.0      1.75          7   5292  
2               2.0    0.0      9.58          5  60553  
3               3.0    1.0      6.75         28   5760  
4               5.0    1.0      2.00          4  10712

In [ ]:
x = train_data.drop('price',axis=1).values
y = train_data['price'].values

array([[ 7212],
       [ 5292],
       [60553],
       ...,
       [14822],
       [ 6450],
       [ 7141]])

In [ ]:
y

array([ 7212,  5292, 60553, ..., 14822,  6450,  7141])

In [ ]:
linear_model = LinearRegression()
linear_model.fit(x,y)

LinearRegression()

In [ ]:
test_data.head()

airline  flight source_city departure_time stops   arrival_time  \
0  Air_India  AI-765     Kolkata        Evening   one          Night   
1    Vistara  UK-747       Delhi  Early_Morning   one          Night   
2  Air_India  AI-570      Mumbai  Early_Morning  zero  Early_Morning   
3    AirAsia  I5-974   Hyderabad          Night   one     Late_Night   
4  Air_India  AI-770     Kolkata          Night   one      Afternoon   

  destination_city     class  duration  days_left  
0            Delhi  Business     28.25          2  
1           Mumbai  Business     13.83         34  
2          Chennai  Business      2.00         30  
3            Delhi   Economy      5.17         26  
4           Mumbai   Economy     16.33         35

In [ ]:
test_data[["airline",	"flight",	"source_city",	"departure_time",	"stops",	"arrival_time",	"destination_city",	"class"]]=encoder.fit_transform(test_data[["airline",	"flight",	"source_city",	"departure_time",	"stops",	"arrival_time",	"destination_city",	"class"]])
test_data = test_data.values

In [ ]:
predicted_test_data = linear_model.predict(test_data)
predicted_train_data = linear_model.predict(x)

In [ ]:
predicted_train_data

array([11027.72162841,  4330.84735092, 56456.18746282, ...,
        9628.13425064, 11122.25125437, 10602.58344138])

In [ ]:
mean_absolute_percentage_error(predicted_train_data, y)

1.2580259847975408

In [ ]:
predicted_train_data

array([11027.72162841,  4330.84735092, 56456.18746282, ...,
        9628.13425064, 11122.25125437, 10602.58344138])

In [ ]:
y

array([ 7212,  5292, 60553, ..., 14822,  6450,  7141])

In [ ]:
oll = pd.DataFrame(columns=["predicted_train_data", 'y'])
oll["predicted_train_data"] =  predicted_train_data
oll["y"] =  y
oll['minus'] = abs(predicted_train_data-y)
oll

predicted_train_data      y        minus
0              11027.721628   7212  3815.721628
1               4330.847351   5292   961.152649
2              56456.187463  60553  4096.812537
3               9010.041344   5760  3250.041344
4               3287.197111  10712  7424.802889
...                     ...    ...          ...
19995           4236.351073   3153  1083.351073
19996           4347.580764   3911   436.580764
19997           9628.134251  14822  5193.865749
19998          11122.251254   6450  4672.251254
19999          10602.583441   7141  3461.583441

[20000 rows x 3 columns]

In [ ]:
y.size

20000

In [ ]:
test_data_1['price'] = predicted_test_data
test_data_1.to_csv('test_pre.csv')

In [ ]:
# prompt: how to converto csv file from np array, columns name is price

df = pd.DataFrame(predicted_test_data, columns=['price'])
df.to_csv('test_pre.csv', index=False)


In [ ]:
h = pd.read_csv('/content/sample_solution.csv')
h['price'] = predicted_test_data
h

id         price
0        1  55791.742848
1        2  53876.242664
2        3  42064.814030
3        4   4202.579405
4        5   5009.587754
...    ...           ...
4995  4996  52535.993841
4996  4997  -1841.124176
4997  4998  49473.232444
4998  4999  49544.090307
4999  5000  51137.923578

[5000 rows x 2 columns]

In [ ]:
h.to_csv('completed.csv',index=False)

In [ ]:
pd.read_csv('completed.csv')

id         price
0        1  55791.742848
1        2  53876.242664
2        3  42064.814030
3        4   4202.579405
4        5   5009.587754
...    ...           ...
4995  4996  52535.993841
4996  4997  -1841.124176
4997  4998  49473.232444
4998  4999  49544.090307
4999  5000  51137.923578

[5000 rows x 2 columns]