In [ ]:
import pandas as pd

In [ ]:
train_set = pd.read_csv("/content/train_data.csv")
test_set = pd.read_csv("/content/test_data.csv")

In [ ]:
train_set.head()

id   airline   flight source_city departure_time stops arrival_time  \
0   1   Vistara   UK-810   Bangalore  Early_Morning   one        Night   
1   2  SpiceJet  SG-5094   Hyderabad        Evening  zero        Night   
2   3   Vistara   UK-846   Bangalore        Morning   one      Evening   
3   4   Vistara   UK-706     Kolkata        Morning   one      Evening   
4   5    Indigo  6E-5394     Chennai  Early_Morning  zero      Morning   

  destination_city     class  duration  days_left  price  
0           Mumbai   Economy     14.25         21   7212  
1          Kolkata   Economy      1.75          7   5292  
2            Delhi  Business      9.58          5  60553  
3        Hyderabad   Economy      6.75         28   5760  
4           Mumbai   Economy      2.00          4  10712

In [ ]:
train_set.info()
train_set.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                20000 non-null  int64  
 1   airline           20000 non-null  object 
 2   flight            20000 non-null  object 
 3   source_city       20000 non-null  object 
 4   departure_time    20000 non-null  object 
 5   stops             20000 non-null  object 
 6   arrival_time      20000 non-null  object 
 7   destination_city  20000 non-null  object 
 8   class             20000 non-null  object 
 9   duration          20000 non-null  float64
 10  days_left         20000 non-null  int64  
 11  price             20000 non-null  int64  
dtypes: float64(1), int64(3), object(8)
memory usage: 1.8+ MB


id      duration     days_left          price
count  20000.000000  20000.000000  20000.000000   20000.000000
mean   10000.500000     12.177627     25.924150   20960.281700
std     5773.647028      7.157944     13.624874   22775.459535
min        1.000000      0.830000      1.000000    1105.000000
25%     5000.750000      6.830000     14.000000    4783.000000
50%    10000.500000     11.250000     26.000000    7425.000000
75%    15000.250000     16.080000     38.000000   42521.000000
max    20000.000000     38.580000     49.000000  114523.000000

In [ ]:
print(train_set.isna().sum())
print("----")
test_set.isna().sum()

id                  0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64
----


id                  0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
dtype: int64

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
ordinal = OrdinalEncoder()
train_set[["airline",	"source_city",	"departure_time",	"stops",	"arrival_time",	"destination_city",	"class"]]=ordinal.fit_transform(train_set[["airline",	"source_city",	"departure_time",	"stops",	"arrival_time",	"destination_city",	"class"]])

In [ ]:
train_set

id  airline   flight  source_city  departure_time  stops  \
0          1      5.0   UK-810          0.0             1.0    0.0   
1          2      4.0  SG-5094          3.0             2.0    2.0   
2          3      5.0   UK-846          0.0             4.0    0.0   
3          4      5.0   UK-706          4.0             4.0    0.0   
4          5      3.0  6E-5394          1.0             1.0    2.0   
...      ...      ...      ...          ...             ...    ...   
19995  19996      3.0  6E-6178          0.0             5.0    0.0   
19996  19997      0.0   I5-582          4.0             4.0    0.0   
19997  19998      5.0   UK-832          1.0             1.0    1.0   
19998  19999      5.0   UK-996          5.0             2.0    0.0   
19999  20000      5.0   UK-776          4.0             2.0    0.0   

       arrival_time  destination_city  class  duration  days_left  price  
0               5.0               5.0    1.0     14.25         21   7212  
1               5.0               4.0    1.0      1.75          7   5292  
2               2.0               2.0    0.0      9.58          5  60553  
3               2.0               3.0    1.0      6.75         28   5760  
4               4.0               5.0    1.0      2.00          4  10712  
...             ...               ...    ...       ...        ...    ...  
19995           1.0               5.0    1.0      7.92         45   3153  
19996           0.0               2.0    1.0      5.83         24   3911  
19997           2.0               0.0    1.0     35.33         17  14822  
19998           4.0               0.0    1.0     16.33         21   6450  
19999           4.0               1.0    1.0     18.25         26   7141  

[20000 rows x 12 columns]

In [ ]:
x = train_set.drop('price',axis=1)
y = train_set['price']

In [ ]:
x

id  airline   flight  source_city  departure_time  stops  \
0          1      5.0   UK-810          0.0             1.0    0.0   
1          2      4.0  SG-5094          3.0             2.0    2.0   
2          3      5.0   UK-846          0.0             4.0    0.0   
3          4      5.0   UK-706          4.0             4.0    0.0   
4          5      3.0  6E-5394          1.0             1.0    2.0   
...      ...      ...      ...          ...             ...    ...   
19995  19996      3.0  6E-6178          0.0             5.0    0.0   
19996  19997      0.0   I5-582          4.0             4.0    0.0   
19997  19998      5.0   UK-832          1.0             1.0    1.0   
19998  19999      5.0   UK-996          5.0             2.0    0.0   
19999  20000      5.0   UK-776          4.0             2.0    0.0   

       arrival_time  destination_city  class  duration  days_left  
0               5.0               5.0    1.0     14.25         21  
1               5.0               4.0    1.0      1.75          7  
2               2.0               2.0    0.0      9.58          5  
3               2.0               3.0    1.0      6.75         28  
4               4.0               5.0    1.0      2.00          4  
...             ...               ...    ...       ...        ...  
19995           1.0               5.0    1.0      7.92         45  
19996           0.0               2.0    1.0      5.83         24  
19997           2.0               0.0    1.0     35.33         17  
19998           4.0               0.0    1.0     16.33         21  
19999           4.0               1.0    1.0     18.25         26  

[20000 rows x 11 columns]

In [ ]:
ohe.fit_transform(x[['flight']])

<20000x1310 sparse matrix of type '<class 'numpy.float64'>'
	with 20000 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer
nums=['airline', 'stops', 'class', 'duration', 'days_left', 'source_city', 'departure_time', 'arrival_time', 'destination_city']
cats=['flight']

num_pipeline = Pipeline([
    ('scaler', MinMaxScaler())
])

cat_pipeline = Pipeline([
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

full_pipeline = ColumnTransformer([
    ('num', num_pipeline, nums),
    ('cat', cat_pipeline, cats)
])

In [ ]:
x = full_pipeline.fit_transform(x)

In [ ]:
x

<20000x1319 sparse matrix of type '<class 'numpy.float64'>'
	with 163284 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.ensemble import RandomForestRegressor
RF_model = RandomForestRegressor()
RF_model.fit(x, y)

RandomForestRegressor()

In [ ]:
test_set[["airline",	"source_city",	"departure_time",	"stops",	"arrival_time",	"destination_city",	"class"]]=ordinal.fit_transform(test_set[["airline",	"source_city",	"departure_time",	"stops",	"arrival_time",	"destination_city",	"class"]])

In [ ]:
test_set

id  airline   flight  source_city  departure_time  stops  \
0        1      1.0   AI-765          4.0             2.0    0.0   
1        2      5.0   UK-747          2.0             1.0    0.0   
2        3      1.0   AI-570          5.0             1.0    2.0   
3        4      0.0   I5-974          3.0             5.0    0.0   
4        5      1.0   AI-770          4.0             5.0    0.0   
...    ...      ...      ...          ...             ...    ...   
4995  4996      1.0   AI-768          4.0             0.0    0.0   
4996  4997      3.0  6E-6214          4.0             4.0    2.0   
4997  4998      1.0   AI-402          4.0             4.0    0.0   
4998  4999      1.0   AI-673          5.0             1.0    0.0   
4999  5000      5.0   UK-774          4.0             5.0    0.0   

      arrival_time  destination_city  class  duration  days_left  
0              5.0               2.0    0.0     28.25          2  
1              5.0               5.0    0.0     13.83         34  
2              1.0               1.0    0.0      2.00         30  
3              3.0               2.0    1.0      5.17         26  
4              0.0               5.0    1.0     16.33         35  
...            ...               ...    ...       ...        ...  
4995           4.0               0.0    0.0     17.42         15  
4996           0.0               5.0    1.0      3.00         40  
4997           5.0               5.0    0.0     11.17         37  
4998           5.0               3.0    0.0     13.33         38  
4999           0.0               2.0    0.0     16.08         49  

[5000 rows x 11 columns]

In [ ]:
test_set = full_pipeline.transform(test_set)

In [ ]:
test_set.toarray()

array([[0.2, 0. , 0. , ..., 0. , 0. , 0. ],
       [1. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0.2, 1. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [0.2, 0. , 0. , ..., 0. , 0. , 0. ],
       [0.2, 0. , 0. , ..., 0. , 0. , 0. ],
       [1. , 0. , 0. , ..., 0. , 0. , 0. ]])

In [ ]:
predictted = RF_model.predict(test_set)

In [ ]:
predictted

array([54493.27, 65630.38, 23394.1 , ..., 50183.24, 50242.85, 62373.53])

In [ ]:
predict_x = RF_model.predict(x)

In [ ]:
predict_x

array([ 7089.69      ,  5393.72      , 60431.46      , ...,
       14370.04166667,  6465.6       ,  7337.1       ])

In [ ]:
y

0         7212
1         5292
2        60553
3         5760
4        10712
         ...  
19995     3153
19996     3911
19997    14822
19998     6450
19999     7141
Name: price, Length: 20000, dtype: int64

In [ ]:
sample = pd.read_csv("/content/sample_solution.csv")
sample['price'] = predictted

In [ ]:
sample.to_csv("completed.csv",index=False)